<?xml version="1.0"?>
<!DOCTYPE CHARACTERISTIC-LIST [
<!ELEMENT CHARACTERISTIC-LIST (CHARACTERISTIC+)>
<!ELEMENT CHARACTERISTIC (PARM*)>
<!ATTLIST CHARACTERISTIC
TYPE CDATA #REQUIRED
VALUE CDATA #IMPLIED
>
<!ELEMENT PARM EMPTY>
<!ATTLIST PARM
NAME CDATA #REQUIRED
VALUE CDATA #REQUIRED
>
]>
<CHARACTERISTIC-LIST>
	<CHARACTERISTIC TYPE="ADDRESS">
		<PARM NAME="BEARER" VALUE="GSM/CSD"/>
		<PARM NAME="PROXY" VALUE="192.122.10.120"/>
		<PARM NAME="CSD_DIALSTRING" VALUE="+358508124002"/>
		<PARM NAME="CSD_AUTHTYPE" VALUE="PAP"/>
		<PARM NAME="CSD_AUTHNAME" VALUE="wapuser"/>
		<PARM NAME="CSD_AUTHSECRET" VALUE="wappassw"/>
		<PARM NAME="CSD_CALLTYPE" VALUE="ANALOGUE"/>
		<PARM NAME="CSD_CALLSPEED" VALUE="AUTO"/>
		<PARM NAME="PROXY_AUTHNAME" VALUE="pxauthname"/>
		<PARM NAME="PROXY_AUTHSECRET" VALUE="pxauthsecret"/>
		<PARM NAME="ISP_NAME" VALUE="World Access ISP"/>
	</CHARACTERISTIC>
	<CHARACTERISTIC TYPE="ADDRESS">
		<PARM NAME="BEARER" VALUE="GSM/SMS"/>
		<PARM NAME="PROXY" VALUE="9400410"/>
		<PARM NAME="SMS_SMSC_ADDRESS" VALUE="+36209400400"/>
	</CHARACTERISTIC>
	<CHARACTERISTIC TYPE="BOOKMARK">
 		<PARM NAME="NAME" VALUE="My favorite page"/>
		<PARM NAME="URL" VALUE="http://www.somewhere.com/index.wml"/>
	</CHARACTERISTIC>
	<CHARACTERISTIC TYPE="URL" VALUE="/startpage/index.wml"/>
	<CHARACTERISTIC TYPE="NAME">
		<PARM NAME="NAME" VALUE="WAP 1009"/>
	</CHARACTERISTIC>
	<CHARACTERISTIC TYPE="PENGUIN">
		<PARM NAME="FISH" VALUE="mackerel"/>
		<PARM NAME="FLIES" VALUE="not likely"/>
		<PARM NAME="FLIP" VALUE="flop"/>
	</CHARACTERISTIC>
</CHARACTERISTIC-LIST>
