<?xml version="1.0"?>
<!DOCTYPE CHARACTERISTIC-LIST [
<!ELEMENT CHARACTERISTIC-LIST (CHARACTERISTIC+)>
<!ELEMENT CHARACTERISTIC (PARM*)>
<!ATTLIST CHARACTERISTIC
	TYPE CDATA #REQUIRED
	VALUE CDATA #IMPLIED
>
<!ELEMENT PARM EMPTY>
<!ATTLIST PARM
	NAME CDATA #REQUIRED
	VALUE CDATA #REQUIRED
>
]>
<CHARACTERISTIC-LIST>
	<CHARACTERISTIC TYPE="ADDRESS">
		<PARM NAME="BEARER" VALUE="GSM/CSD"/>
		<PARM NAME="PROXY" VALUE="111.128.129.254"/>
		<PARM NAME="CSD_DIALSTRING" VALUE="+44207555333"/>
	</CHARACTERISTIC>
	<CHARACTERISTIC TYPE="ADDRESS">
		<PARM NAME="BEARER" VALUE="GSM/SMS"/>
		<PARM NAME="PROXY" VALUE="55599900"/>
		<PARM NAME="SMS_SMSC_ADDRESS" VALUE="+4410444999"/>
	</CHARACTERISTIC>
    <CHARACTERISTIC TYPE="BOOKMARK">
        <PARM NAME="NAME" VALUE="Glorious WAP"/>
		<PARM NAME="URL" VALUE="http://www.WAP-World.com/"/>
 	</CHARACTERISTIC>
    <CHARACTERISTIC TYPE="URL" VALUE="/min-index.wml"/>
	<CHARACTERISTIC TYPE="NAME">
		<PARM NAME="NAME" VALUE="WAP World"/>
	</CHARACTERISTIC>
    <CHARACTERISTIC TYPE="ID">
		<PARM NAME="NAME" VALUE="WAPP 0079"/>
	</CHARACTERISTIC>
</CHARACTERISTIC-LIST>
