<?xml version="1.0"?>
<!DOCTYPE CHARACTERISTIC-LIST [
<!ELEMENT CHARACTERISTIC-LIST (CHARACTERISTIC+)>
<!ELEMENT CHARACTERISTIC (PARM*)>
<!ATTLIST CHARACTERISTIC
	TYPE CDATA #REQUIRED
	VALUE CDATA #IMPLIED
>
<!ELEMENT PARM EMPTY>
<!ATTLIST PARM
	NAME CDATA #REQUIRED
	VALUE CDATA #REQUIRED
>
]>
<CHARACTERISTIC-LIST>
    <CHARACTERISTIC TYPE="ADDRESS">
		<PARM NAME="BEARER" VALUE="GSM/USSD"/>
        <PARM NAME="PROXY_TYPE" VALUE="IPV4"/>
		<PARM NAME="PROXY" VALUE="195.134.200.01"/>
		<PARM NAME="PORT" VALUE="9202"/>
		<PARM NAME="USSD_SERVICE_CODE VALUE="+4489347834143"/>
	</CHARACTERISTIC>
    <CHARACTERISTIC TYPE="BOOKMARK">
 		<PARM NAME="NAME" VALUE="My favourite page"/>
		<PARM NAME="URL" VALUE="http://www.somewhere.com/index1.wml"/>
	</CHARACTERISTIC>
    <CHARACTERISTIC TYPE="URL" VALUE="/homepage/index.wml" />
	<CHARACTERISTIC TYPE="NAME">
		<PARM NAME="NAME" VALUE="WAPP 2002"/>
    </CHARACTERISTIC>
    <CHARACTERISTIC TYPE="ID">
		<PARM NAME="NAME" VALUE="12345678"/>
	</CHARACTERISTIC>
</CHARACTERISTIC-LIST>	
