<?xml version="1.0"?>
<!DOCTYPE CHARACTERISTIC-LIST [
<!ELEMENT CHARACTERISTIC-LIST (CHARACTERISTIC+)>
<!ELEMENT CHARACTERISTIC (PARM*)>
<!ATTLIST CHARACTERISTIC
	TYPE CDATA #REQUIRED
	VALUE CDATA #IMPLIED
>
<!ELEMENT PARM EMPTY>
<!ATTLIST PARM
	NAME CDATA #REQUIRED
	VALUE CDATA #REQUIRED
>
]>
<CHARACTERISTIC-LIST>
	<CHARACTERISTIC TYPE="ADDRESS">
		<PARM NAME="BEARER" VALUE="GSM/CSD"/>
		<PARM NAME="PROXY" VALUE="111.128.110.100"/>
		<PARM NAME="PORT" VALUE="9202"/>
		<PARM NAME="CSD_DIALSTRING" VALUE="+4499119922"/>
		<PARM NAME="CSD_AUTHTYPE" VALUE="PAP"/>
		<PARM NAME="CSD_AUTHNAME" VALUE="user3"/>
		<PARM NAME="CSD_AUTHSECRET" VALUE="psword3"/>
		<PARM NAME="CSD_CALLSPEED" VALUE="ISDN"/>
		<PARM NAME="CSD_CALLTYPE" VALUE="43200"/>
		<PARM NAME="PROXY_AUTHNAME" VALUE="proxy3"/>
		<PARM NAME="PROXY_AUTHSECRET" VALUE="proxy3"/>
		<PARM NAME="ISP_NAME" VALUE="Little ISP"/>
	</CHARACTERISTIC>
    <CHARACTERISTIC TYPE="BOOKMARK">
        <PARM NAME="NAME" VALUE="Glorious WAP"/>
		<PARM NAME="URL" VALUE="http://www.WAP-World.com"/>
 	</CHARACTERISTIC>
    <CHARACTERISTIC TYPE="URL" VALUE="/index1.wml"/>
	<CHARACTERISTIC TYPE="NAME">
		<PARM NAME="NAME" VALUE="WAP World"/>
	</CHARACTERISTIC>
    <CHARACTERISTIC TYPE="ID">
		<PARM NAME="NAME" VALUE="WAPP 0081"/>
	</CHARACTERISTIC>
</CHARACTERISTIC-LIST>
